package com.cnlaunch.x431pro.utils.p286f;

import android.content.Context;
import com.cnlaunch.diagnosemodule.utils.DiagnoseConstants;
import com.ifoer.expedition.pro.R;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/* renamed from: com.cnlaunch.x431pro.utils.f.b */
/* loaded from: classes.dex */
public final class AsiaIcon {
    /* renamed from: a */
    public static List<HashMap<String, String>> m4979a(Context context) {
        ArrayList arrayList = new ArrayList();
        new HashMap();
        HashMap hashMap = new HashMap();
        hashMap.put("softPackageId", "DEMO");
        hashMap.put("name", context.getString(R.string.DEMO));
        hashMap.put("name_zh", "2131689583");
        hashMap.put("icon", "icon_demo");
        hashMap.put("areaId", "ASIA");
        hashMap.put("sname", "A09");
        hashMap.put("sname_zh", "09");
        arrayList.add(hashMap);
        HashMap hashMap2 = new HashMap();
        hashMap2.put("softPackageId", "EOBD2");
        hashMap2.put("name", context.getString(R.string.EOBD2));
        hashMap2.put("name_zh", "2131689623");
        hashMap2.put("icon", "icon_eobd2");
        hashMap2.put("areaId", "ASIA");
        hashMap2.put("sname", "A10");
        hashMap2.put("sname_zh", DiagnoseConstants.DATA_TYPE_FROM_APK_TO_SO_SET_MENUPATH);
        arrayList.add(hashMap2);
        HashMap hashMap3 = new HashMap();
        hashMap3.put("softPackageId", "ACURA");
        hashMap3.put("name", context.getString(R.string.ACURA));
        hashMap3.put("name_zh", "2131689473");
        hashMap3.put("icon", "icon_acura");
        hashMap3.put("areaId", "ASIA");
        hashMap3.put("sname", context.getString(R.string.ACURA));
        hashMap3.put("sname_zh", "OUGE");
        arrayList.add(hashMap3);
        HashMap hashMap4 = new HashMap();
        hashMap4.put("softPackageId", "HOLDEN");
        hashMap4.put("name", context.getString(R.string.HOLDEN));
        hashMap4.put("name_zh", "2131689691");
        hashMap4.put("icon", "icon_holden");
        hashMap4.put("areaId", "USA");
        hashMap4.put("sname", context.getString(R.string.HOLDEN));
        hashMap4.put("sname_zh", "HUODUN");
        arrayList.add(hashMap4);
        HashMap hashMap5 = new HashMap();
        hashMap5.put("softPackageId", "DAEWOO");
        hashMap5.put("name", context.getString(R.string.DAEWOO));
        hashMap5.put("name_zh", "2131689579");
        hashMap5.put("icon", "icon_daewoo");
        hashMap5.put("areaId", "ASIA");
        hashMap5.put("sname", context.getString(R.string.DAEWOO));
        hashMap5.put("sname_zh", "DAYU");
        arrayList.add(hashMap5);
        HashMap hashMap6 = new HashMap();
        hashMap6.put("softPackageId", "DAIHATSU");
        hashMap6.put("name", context.getString(R.string.DAIHATSU));
        hashMap6.put("name_zh", "2131689581");
        hashMap6.put("icon", "icon_daihatsu");
        hashMap6.put("areaId", "ASIA");
        hashMap6.put("sname", context.getString(R.string.DAIHATSU));
        hashMap6.put("sname_zh", "DAFA");
        arrayList.add(hashMap6);
        HashMap hashMap7 = new HashMap();
        hashMap7.put("softPackageId", "HM");
        hashMap7.put("name", context.getString(R.string.HM));
        hashMap7.put("name_zh", "2131689689");
        hashMap7.put("icon", "icon_hm");
        hashMap7.put("areaId", "ASIA");
        hashMap7.put("sname", context.getString(R.string.HM));
        hashMap7.put("sname_zh", "HM");
        arrayList.add(hashMap7);
        HashMap hashMap8 = new HashMap();
        hashMap8.put("softPackageId", "HONDA");
        hashMap8.put("name", context.getString(R.string.HONDA));
        hashMap8.put("name_zh", "2131689695");
        hashMap8.put("icon", "icon_honda");
        hashMap8.put("areaId", "ASIA");
        hashMap8.put("sname", context.getString(R.string.HONDA));
        hashMap8.put("sname_zh", "BENTIANCHEXI");
        arrayList.add(hashMap8);
        HashMap hashMap9 = new HashMap();
        hashMap9.put("softPackageId", "HYUNDAI");
        hashMap9.put("name", context.getString(R.string.HYUNDAI));
        hashMap9.put("name_zh", "2131689713");
        hashMap9.put("icon", "icon_hyundai");
        hashMap9.put("areaId", "ASIA");
        hashMap9.put("sname", context.getString(R.string.HYUNDAI));
        hashMap9.put("sname_zh", "XIANDAI");
        arrayList.add(hashMap9);
        HashMap hashMap10 = new HashMap();
        hashMap10.put("softPackageId", "INDIANMAHINDRA");
        hashMap10.put("name", context.getString(R.string.INDIANMAHINDRA));
        hashMap10.put("name_zh", "2131689737");
        hashMap10.put("icon", "icon_mahindra");
        hashMap10.put("areaId", "ASIA");
        hashMap10.put("sname", context.getString(R.string.INDIANMAHINDRA));
        hashMap10.put("sname_zh", "YINDUMAHENGDA");
        arrayList.add(hashMap10);
        HashMap hashMap11 = new HashMap();
        hashMap11.put("softPackageId", "INDIANMARUTI");
        hashMap11.put("name", context.getString(R.string.INDIANMARUTI));
        hashMap11.put("name_zh", "2131689739");
        hashMap11.put("icon", "icon_maruti");
        hashMap11.put("areaId", "ASIA");
        hashMap11.put("sname", context.getString(R.string.INDIANMARUTI));
        hashMap11.put("sname_zh", "INDIANMARUTI");
        arrayList.add(hashMap11);
        HashMap hashMap12 = new HashMap();
        hashMap12.put("softPackageId", "INDIANTATA");
        hashMap12.put("name", context.getString(R.string.INDIANTATA));
        hashMap12.put("name_zh", "2131689741");
        hashMap12.put("icon", "icon_tata");
        hashMap12.put("areaId", "ASIA");
        hashMap12.put("sname", context.getString(R.string.INDIANTATA));
        hashMap12.put("sname_zh", "YINDUTATA");
        arrayList.add(hashMap12);
        HashMap hashMap13 = new HashMap();
        hashMap13.put("softPackageId", "INDONESIADAIHATSU");
        hashMap13.put("name", context.getString(R.string.INDONESIADAIHATSU));
        hashMap13.put("name_zh", "2131689743");
        hashMap13.put("icon", "icon_indonesiadaihatsu");
        hashMap13.put("areaId", "ASIA");
        hashMap13.put("sname", context.getString(R.string.INDONESIADAIHATSU));
        hashMap13.put("sname_zh", "YINNIDAFA");
        arrayList.add(hashMap13);
        HashMap hashMap14 = new HashMap();
        hashMap14.put("softPackageId", "INDONESIASUZUKI");
        hashMap14.put("name", context.getString(R.string.INDONESIASUZUKI));
        hashMap14.put("name_zh", "2131689745");
        hashMap14.put("icon", "icon_indonesiasuzuki");
        hashMap14.put("areaId", "ASIA");
        hashMap14.put("sname", context.getString(R.string.INDONESIASUZUKI));
        hashMap14.put("sname_zh", "YINNILINGMU");
        arrayList.add(hashMap14);
        HashMap hashMap15 = new HashMap();
        hashMap15.put("softPackageId", "INFINITI");
        hashMap15.put("name", context.getString(R.string.INFINITI));
        hashMap15.put("name_zh", "2131689747");
        hashMap15.put("icon", "icon_infiniti");
        hashMap15.put("areaId", "ASIA");
        hashMap15.put("sname", context.getString(R.string.INFINITI));
        hashMap15.put("sname_zh", "YINGFEINIDI");
        arrayList.add(hashMap15);
        HashMap hashMap16 = new HashMap();
        hashMap16.put("softPackageId", "IRCITROEN");
        hashMap16.put("name", context.getString(R.string.IRCITROEN));
        hashMap16.put("name_zh", "2131689749");
        hashMap16.put("icon", "icon_ircitroen");
        hashMap16.put("areaId", "ASIA");
        hashMap16.put("sname", context.getString(R.string.IRCITROEN));
        hashMap16.put("sname_zh", "YILANGXUETIELONG");
        arrayList.add(hashMap16);
        HashMap hashMap17 = new HashMap();
        hashMap17.put("softPackageId", "IRKIA");
        hashMap17.put("name", context.getString(R.string.IRKIA));
        hashMap17.put("name_zh", "2131689751");
        hashMap17.put("icon", "icon_irkia");
        hashMap17.put("areaId", "ASIA");
        hashMap17.put("sname", context.getString(R.string.IRKIA));
        hashMap17.put("sname_zh", "YILANGQIYA");
        arrayList.add(hashMap17);
        HashMap hashMap18 = new HashMap();
        hashMap18.put("softPackageId", "IRPEUGEOT");
        hashMap18.put("name", context.getString(R.string.IRPEUGEOT));
        hashMap18.put("name_zh", "2131689753");
        hashMap18.put("icon", "icon_irpeugeot");
        hashMap18.put("areaId", "ASIA");
        hashMap18.put("sname", context.getString(R.string.IRPEUGEOT));
        hashMap18.put("sname_zh", "YILANGBIAOZHI");
        arrayList.add(hashMap18);
        HashMap hashMap19 = new HashMap();
        hashMap19.put("softPackageId", "JPISUZU");
        hashMap19.put("name", context.getString(R.string.JPISUZU));
        hashMap19.put("name_zh", "2131689813");
        hashMap19.put("icon", "icon_jpisuzu");
        hashMap19.put("areaId", "ASIA");
        hashMap19.put("sname", context.getString(R.string.JPISUZU));
        hashMap19.put("sname_zh", "WUSHILING");
        arrayList.add(hashMap19);
        HashMap hashMap20 = new HashMap();
        hashMap20.put("softPackageId", "KIA");
        hashMap20.put("name", context.getString(R.string.KIA));
        hashMap20.put("name_zh", "2131689823");
        hashMap20.put("icon", "icon_kia");
        hashMap20.put("areaId", "ASIA");
        hashMap20.put("sname", context.getString(R.string.KIA));
        hashMap20.put("sname_zh", "QIYA");
        arrayList.add(hashMap20);
        HashMap hashMap21 = new HashMap();
        hashMap21.put("softPackageId", "KOREAHYUNDAI");
        hashMap21.put("name", context.getString(R.string.KOREAHYUNDAI));
        hashMap21.put("name_zh", "2131689834");
        hashMap21.put("icon", "icon_koreahyundai");
        hashMap21.put("areaId", "ASIA");
        hashMap21.put("sname", context.getString(R.string.KOREAHYUNDAI));
        hashMap21.put("sname_zh", "HANGUOXIANDAI");
        arrayList.add(hashMap21);
        HashMap hashMap22 = new HashMap();
        hashMap22.put("softPackageId", "KOREAKIA");
        hashMap22.put("name", "KIA (KOREA)");
        hashMap22.put("name_zh", "2131689836");
        hashMap22.put("icon", "icon_kia");
        hashMap22.put("areaId", "ASIA");
        hashMap22.put("sname", context.getString(R.string.KOREAKIA));
        hashMap22.put("sname_zh", "HANGUOQIYA");
        arrayList.add(hashMap22);
        HashMap hashMap23 = new HashMap();
        hashMap23.put("softPackageId", "LEXUS");
        hashMap23.put("name", context.getString(R.string.LEXUS));
        hashMap23.put("name_zh", "2131689842");
        hashMap23.put("icon", "icon_lexus");
        hashMap23.put("areaId", "ASIA");
        hashMap23.put("sname", context.getString(R.string.LEXUS));
        hashMap23.put("sname_zh", "LEIKESASI");
        arrayList.add(hashMap23);
        HashMap hashMap24 = new HashMap();
        hashMap24.put("softPackageId", "MAHINDRA");
        hashMap24.put("name", context.getString(R.string.MAHINDRA));
        hashMap24.put("name_zh", "2131689860");
        hashMap24.put("icon", "icon_mahindra");
        hashMap24.put("areaId", "ASIA");
        hashMap24.put("sname", context.getString(R.string.MAHINDRA));
        hashMap24.put("sname_zh", "MAHENGDA");
        arrayList.add(hashMap24);
        HashMap hashMap25 = new HashMap();
        hashMap25.put("softPackageId", "MALAYSIA PERODUA");
        hashMap25.put("name", context.getString(R.string.MALAYSIAPERODUA));
        hashMap25.put("name_zh", "2131689862");
        hashMap25.put("icon", "icon_perodua");
        hashMap25.put("areaId", "ASIA");
        hashMap25.put("sname", context.getString(R.string.MALAYSIAPERODUA));
        hashMap25.put("sname_zh", "MALAYSIAPERODUA");
        arrayList.add(hashMap25);
        HashMap hashMap26 = new HashMap();
        hashMap26.put("softPackageId", "MALAYSIA PROTON");
        hashMap26.put("name", context.getString(R.string.MALAYSIAPROTON));
        hashMap26.put("name_zh", "2131689864");
        hashMap26.put("icon", "icon_proton");
        hashMap26.put("areaId", "ASIA");
        hashMap26.put("sname", context.getString(R.string.MALAYSIAPROTON));
        hashMap26.put("sname_zh", "MALAIXIYABAOTENG");
        arrayList.add(hashMap26);
        HashMap hashMap27 = new HashMap();
        hashMap27.put("softPackageId", "MARUTI");
        hashMap27.put("name", context.getString(R.string.MARUTI));
        hashMap27.put("name_zh", "2131689866");
        hashMap27.put("icon", "icon_maruti");
        hashMap27.put("areaId", "ASIA");
        hashMap27.put("sname", context.getString(R.string.MARUTI));
        hashMap27.put("sname_zh", "MARUTI");
        arrayList.add(hashMap27);
        HashMap hashMap28 = new HashMap();
        hashMap28.put("softPackageId", "MAZDA");
        hashMap28.put("name", context.getString(R.string.MAZDA));
        hashMap28.put("name_zh", "2131689868");
        hashMap28.put("icon", "icon_mazda");
        hashMap28.put("areaId", "ASIA");
        hashMap28.put("sname", context.getString(R.string.MAZDA));
        hashMap28.put("sname_zh", "MAZIDACHEXI");
        arrayList.add(hashMap28);
        HashMap hashMap29 = new HashMap();
        hashMap29.put("softPackageId", "MITSUBISHI");
        hashMap29.put("name", context.getString(R.string.MITSUBISHI));
        hashMap29.put("name_zh", "2131689874");
        hashMap29.put("icon", "icon_mitsubishi");
        hashMap29.put("areaId", "ASIA");
        hashMap29.put("sname", context.getString(R.string.MITSUBISHI));
        hashMap29.put("sname_zh", "SANLINGCHEXI");
        arrayList.add(hashMap29);
        HashMap hashMap30 = new HashMap();
        hashMap30.put("softPackageId", "NISSAN");
        hashMap30.put("name", context.getString(R.string.NISSAN));
        hashMap30.put("name_zh", "2131689884");
        hashMap30.put("icon", "icon_nissan");
        hashMap30.put("areaId", "ASIA");
        hashMap30.put("sname", context.getString(R.string.NISSAN));
        hashMap30.put("sname_zh", "RICHANCHEXI");
        arrayList.add(hashMap30);
        HashMap hashMap31 = new HashMap();
        hashMap31.put("softPackageId", "PERODUA");
        hashMap31.put("name", context.getString(R.string.PERODUA));
        hashMap31.put("name_zh", "2131689901");
        hashMap31.put("icon", "icon_perodua");
        hashMap31.put("areaId", "ASIA");
        hashMap31.put("sname", context.getString(R.string.PERODUA));
        hashMap31.put("sname_zh", "PERODUA");
        arrayList.add(hashMap31);
        HashMap hashMap32 = new HashMap();
        hashMap32.put("softPackageId", "PROTON");
        hashMap32.put("name", context.getString(R.string.PROTON));
        hashMap32.put("name_zh", "2131689907");
        hashMap32.put("icon", "icon_proton");
        hashMap32.put("areaId", "ASIA");
        hashMap32.put("sname", context.getString(R.string.PROTON));
        hashMap32.put("sname_zh", "BAOTENG");
        arrayList.add(hashMap32);
        HashMap hashMap33 = new HashMap();
        hashMap33.put("softPackageId", "SAMSUNG");
        hashMap33.put("name", context.getString(R.string.SAMSUNG));
        hashMap33.put("name_zh", "2131689972");
        hashMap33.put("icon", "icon_samsung");
        hashMap33.put("areaId", "ASIA");
        hashMap33.put("sname", context.getString(R.string.SAMSUNG));
        hashMap33.put("sname_zh", "SANXING");
        arrayList.add(hashMap33);
        HashMap hashMap34 = new HashMap();
        hashMap34.put("softPackageId", "SSANGYONG");
        hashMap34.put("name", context.getString(R.string.SSANGYONG));
        hashMap34.put("name_zh", "2131690000");
        hashMap34.put("icon", "icon_ssangyong");
        hashMap34.put("areaId", "ASIA");
        hashMap34.put("sname", context.getString(R.string.SSANGYONG));
        hashMap34.put("sname_zh", "SHUANGLONG");
        arrayList.add(hashMap34);
        HashMap hashMap35 = new HashMap();
        hashMap35.put("softPackageId", "SUBARU");
        hashMap35.put("name", context.getString(R.string.SUBARU));
        hashMap35.put("name_zh", "2131690002");
        hashMap35.put("icon", "icon_subaru");
        hashMap35.put("areaId", "ASIA");
        hashMap35.put("sname", context.getString(R.string.SUBARU));
        hashMap35.put("sname_zh", "SIBALU");
        arrayList.add(hashMap35);
        HashMap hashMap36 = new HashMap();
        hashMap36.put("softPackageId", "SUZUKI");
        hashMap36.put("name", context.getString(R.string.SUZUKI));
        hashMap36.put("name_zh", "2131690006");
        hashMap36.put("icon", "icon_suzuki");
        hashMap36.put("areaId", "ASIA");
        hashMap36.put("sname", context.getString(R.string.SUZUKI));
        hashMap36.put("sname_zh", "LINGMU");
        arrayList.add(hashMap36);
        HashMap hashMap37 = new HashMap();
        hashMap37.put("softPackageId", "TATA");
        hashMap37.put("name", context.getString(R.string.TATA));
        hashMap37.put("name_zh", "2131690022");
        hashMap37.put("icon", "icon_tata");
        hashMap37.put("areaId", "ASIA");
        hashMap37.put("sname", context.getString(R.string.TATA));
        hashMap37.put("sname_zh", "TATA");
        arrayList.add(hashMap37);
        HashMap hashMap38 = new HashMap();
        hashMap38.put("softPackageId", "TLISUZU");
        hashMap38.put("name", context.getString(R.string.TLISUZU));
        hashMap38.put("name_zh", "2131690036");
        hashMap38.put("icon", "icon_tlisuzu");
        hashMap38.put("areaId", "ASIA");
        hashMap38.put("sname", context.getString(R.string.TLISUZU));
        hashMap38.put("sname_zh", "TAIGUOWUSHILING");
        arrayList.add(hashMap38);
        HashMap hashMap39 = new HashMap();
        hashMap39.put("softPackageId", "TOYOTA");
        hashMap39.put("name", context.getString(R.string.TOYOTA));
        hashMap39.put("name_zh", "2131690042");
        hashMap39.put("icon", "icon_toyota");
        hashMap39.put("areaId", "ASIA");
        hashMap39.put("sname", context.getString(R.string.TOYOTA));
        hashMap39.put("sname_zh", "FENGTIANCHEXI");
        arrayList.add(hashMap39);
        HashMap hashMap40 = new HashMap();
        hashMap40.put("softPackageId", "LUXGEN");
        hashMap40.put("name", context.getString(R.string.LUXGEN));
        hashMap40.put("name_zh", "2131689858");
        hashMap40.put("icon", "icon_luxgen");
        hashMap40.put("areaId", "ASIA");
        hashMap40.put("sname", context.getString(R.string.LUXGEN));
        hashMap40.put("sname_zh", "LUXGEN");
        arrayList.add(hashMap40);
        HashMap hashMap41 = new HashMap();
        hashMap41.put("softPackageId", "SAIPA");
        hashMap41.put("name", context.getString(R.string.SAIPA));
        hashMap41.put("name_zh", "2131689970");
        hashMap41.put("icon", "icon_demo");
        hashMap41.put("areaId", "ASIA");
        hashMap41.put("sname", context.getString(R.string.SAIPA));
        hashMap41.put("sname_zh", "SAIPA");
        arrayList.add(hashMap41);
        return arrayList;
    }
}
