package com.cnlaunch.x431pro.utils.p286f;

import android.content.Context;
import com.cnlaunch.diagnosemodule.utils.DiagnoseConstants;
import com.ifoer.expedition.pro.R;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/* renamed from: com.cnlaunch.x431pro.utils.f.l */
/* loaded from: classes.dex */
public final class EuroIcon {
    /* renamed from: a */
    public static List<HashMap<String, String>> m4939a(Context context) {
        ArrayList arrayList = new ArrayList();
        new HashMap();
        HashMap hashMap = new HashMap();
        hashMap.put("softPackageId", "DEMO");
        hashMap.put("name", context.getString(R.string.DEMO));
        hashMap.put("name_zh", "2131689583");
        hashMap.put("icon", "icon_demo");
        hashMap.put("areaId", "EUROPE");
        hashMap.put("sname", "A09");
        hashMap.put("sname_zh", "09");
        arrayList.add(hashMap);
        HashMap hashMap2 = new HashMap();
        hashMap2.put("softPackageId", "EOBD2");
        hashMap2.put("name", context.getString(R.string.EOBD2));
        hashMap2.put("name_zh", "2131689623");
        hashMap2.put("icon", "icon_eobd2");
        hashMap2.put("areaId", "EUROPE");
        hashMap2.put("sname", "A10");
        hashMap2.put("sname_zh", DiagnoseConstants.DATA_TYPE_FROM_APK_TO_SO_SET_MENUPATH);
        arrayList.add(hashMap2);
        HashMap hashMap3 = new HashMap();
        hashMap3.put("softPackageId", "AUDI");
        hashMap3.put("name", context.getString(R.string.AUDI));
        hashMap3.put("name_zh", "2131689479");
        hashMap3.put("icon", "icon_audi");
        hashMap3.put("areaId", "EUROPE");
        hashMap3.put("sname", context.getString(R.string.AUDI));
        hashMap3.put("sname_zh", "AODI");
        arrayList.add(hashMap3);
        HashMap hashMap4 = new HashMap();
        hashMap4.put("softPackageId", "BENZ");
        hashMap4.put("name", context.getString(R.string.BENZ));
        hashMap4.put("name_zh", "2131689499");
        hashMap4.put("icon", "icon_benz");
        hashMap4.put("areaId", "EUROPE");
        hashMap4.put("sname", context.getString(R.string.BENZ));
        hashMap4.put("sname_zh", "BENCHICHEXI");
        arrayList.add(hashMap4);
        HashMap hashMap5 = new HashMap();
        hashMap5.put("softPackageId", "BMW");
        hashMap5.put("name", context.getString(R.string.BMW));
        hashMap5.put("name_zh", "2131689509");
        hashMap5.put("icon", "icon_bmw");
        hashMap5.put("areaId", "EUROPE");
        hashMap5.put("sname", context.getString(R.string.BMW));
        hashMap5.put("sname_zh", "BAOMACHEXI");
        arrayList.add(hashMap5);
        HashMap hashMap6 = new HashMap();
        hashMap6.put("softPackageId", "CITROEN");
        hashMap6.put("name", context.getString(R.string.CITROEN));
        hashMap6.put("name_zh", "2131689563");
        hashMap6.put("icon", "icon_citroen");
        hashMap6.put("areaId", "EUROPE");
        hashMap6.put("sname", context.getString(R.string.CITROEN));
        hashMap6.put("sname_zh", "XUETIELONG");
        arrayList.add(hashMap6);
        HashMap hashMap7 = new HashMap();
        hashMap7.put("softPackageId", "DACIA");
        hashMap7.put("name", context.getString(R.string.DACIA));
        hashMap7.put("name_zh", "2131689575");
        hashMap7.put("icon", "icon_dacia");
        hashMap7.put("areaId", "EUROPE");
        hashMap7.put("sname", context.getString(R.string.DACIA));
        hashMap7.put("sname_zh", "DAXIYA");
        arrayList.add(hashMap7);
        HashMap hashMap8 = new HashMap();
        hashMap8.put("softPackageId", "EUROFORD");
        hashMap8.put("name", context.getString(R.string.EUROFORD));
        hashMap8.put("name_zh", "2131689625");
        hashMap8.put("icon", "icon_euroford");
        hashMap8.put("areaId", "EUROPE");
        hashMap8.put("sname", context.getString(R.string.EUROFORD));
        hashMap8.put("sname_zh", "OUZHOUFUTE");
        arrayList.add(hashMap8);
        HashMap hashMap9 = new HashMap();
        hashMap9.put("softPackageId", "FIAT");
        hashMap9.put("name", context.getString(R.string.FIAT));
        hashMap9.put("name_zh", "2131689628");
        hashMap9.put("icon", "icon_fiat");
        hashMap9.put("areaId", "EUROPE");
        hashMap9.put("sname", context.getString(R.string.FIAT));
        hashMap9.put("sname_zh", "FEIYATECHEXI");
        arrayList.add(hashMap9);
        HashMap hashMap10 = new HashMap();
        hashMap10.put("softPackageId", "GAZ");
        hashMap10.put("name", context.getString(R.string.GAZ));
        hashMap10.put("name_zh", "2131689653");
        hashMap10.put("icon", "icon_gaz");
        hashMap10.put("areaId", "EUROPE");
        hashMap10.put("sname", context.getString(R.string.GAZ));
        hashMap10.put("sname_zh", "GEZIGAZ");
        arrayList.add(hashMap10);
        HashMap hashMap11 = new HashMap();
        hashMap11.put("softPackageId", "GMSA");
        hashMap11.put("name", context.getString(R.string.GMSA));
        hashMap11.put("name_zh", "2131689656");
        hashMap11.put("icon", "icon_gmsa");
        hashMap11.put("areaId", "EUROPE");
        hashMap11.put("sname", context.getString(R.string.GMSA));
        hashMap11.put("sname_zh", "NANFEIOUBAO");
        arrayList.add(hashMap11);
        HashMap hashMap12 = new HashMap();
        hashMap12.put("softPackageId", "JAGUAR");
        hashMap12.put("name", context.getString(R.string.JAGUAR));
        hashMap12.put("name_zh", "2131689773");
        hashMap12.put("icon", "icon_jaguar");
        hashMap12.put("areaId", "EUROPE");
        hashMap12.put("sname", context.getString(R.string.JAGUAR));
        hashMap12.put("sname_zh", "JIEBAO");
        arrayList.add(hashMap12);
        HashMap hashMap13 = new HashMap();
        hashMap13.put("softPackageId", "LANCIA");
        hashMap13.put("name", context.getString(R.string.LANCIA));
        hashMap13.put("name_zh", "2131689838");
        hashMap13.put("icon", "icon_lancia");
        hashMap13.put("areaId", "EUROPE");
        hashMap13.put("sname", context.getString(R.string.LANCIA));
        hashMap13.put("sname_zh", "LANQIYA");
        arrayList.add(hashMap13);
        HashMap hashMap14 = new HashMap();
        hashMap14.put("softPackageId", "LANDROVER");
        hashMap14.put("name", context.getString(R.string.LANDROVER));
        hashMap14.put("name_zh", "2131689840");
        hashMap14.put("icon", "icon_landrover");
        hashMap14.put("areaId", "EUROPE");
        hashMap14.put("sname", context.getString(R.string.LANDROVER));
        hashMap14.put("sname_zh", "LUHU");
        arrayList.add(hashMap14);
        HashMap hashMap15 = new HashMap();
        hashMap15.put("softPackageId", "MINI");
        hashMap15.put("name", context.getString(R.string.MINI));
        hashMap15.put("name_zh", "2131689872");
        hashMap15.put("icon", "icon_mini");
        hashMap15.put("areaId", "EUROPE");
        hashMap15.put("sname", context.getString(R.string.MINI));
        hashMap15.put("sname_zh", "MINI");
        arrayList.add(hashMap15);
        HashMap hashMap16 = new HashMap();
        hashMap16.put("softPackageId", "OPEL");
        hashMap16.put("name", context.getString(R.string.OPEL));
        hashMap16.put("name_zh", "2131689899");
        hashMap16.put("icon", "icon_opel");
        hashMap16.put("areaId", "EUROPE");
        hashMap16.put("sname", context.getString(R.string.OPEL));
        hashMap16.put("sname_zh", "OUBAOCHEXI");
        arrayList.add(hashMap16);
        HashMap hashMap17 = new HashMap();
        hashMap17.put("softPackageId", "PEUGEOT");
        hashMap17.put("name", context.getString(R.string.PEUGEOT));
        hashMap17.put("name_zh", "2131689903");
        hashMap17.put("icon", "icon_peugeot");
        hashMap17.put("areaId", "EUROPE");
        hashMap17.put("sname", context.getString(R.string.PEUGEOT));
        hashMap17.put("sname_zh", "BIAOZHI");
        arrayList.add(hashMap17);
        HashMap hashMap18 = new HashMap();
        hashMap18.put("softPackageId", "PORSCHE");
        hashMap18.put("name", context.getString(R.string.PORSCHE));
        hashMap18.put("name_zh", "2131689905");
        hashMap18.put("icon", "icon_porsche");
        hashMap18.put("areaId", "EUROPE");
        hashMap18.put("sname", context.getString(R.string.PORSCHE));
        hashMap18.put("sname_zh", "BAOSHIJIE");
        arrayList.add(hashMap18);
        HashMap hashMap19 = new HashMap();
        hashMap19.put("softPackageId", "RENAULT");
        hashMap19.put("name", context.getString(R.string.RENAULT));
        hashMap19.put("name_zh", "2131689933");
        hashMap19.put("icon", "icon_renault");
        hashMap19.put("areaId", "EUROPE");
        hashMap19.put("sname", context.getString(R.string.RENAULT));
        hashMap19.put("sname_zh", "LEINUO");
        arrayList.add(hashMap19);
        HashMap hashMap20 = new HashMap();
        hashMap20.put("softPackageId", "ROMEO");
        hashMap20.put("name", context.getString(R.string.ROMEO));
        hashMap20.put("name_zh", "2131689955");
        hashMap20.put("icon", "icon_romeo");
        hashMap20.put("areaId", "EUROPE");
        hashMap20.put("sname", context.getString(R.string.ROMEO));
        hashMap20.put("sname_zh", "LUOMIOU");
        arrayList.add(hashMap20);
        HashMap hashMap21 = new HashMap();
        hashMap21.put("softPackageId", "ROVER");
        hashMap21.put("name", context.getString(R.string.ROVER));
        hashMap21.put("name_zh", "2131689957");
        hashMap21.put("icon", "icon_rover");
        hashMap21.put("areaId", "EUROPE");
        hashMap21.put("sname", context.getString(R.string.ROVER));
        hashMap21.put("sname_zh", "LUOFU");
        arrayList.add(hashMap21);
        HashMap hashMap22 = new HashMap();
        hashMap22.put("softPackageId", "SAAB");
        hashMap22.put("name", context.getString(R.string.SAAB));
        hashMap22.put("name_zh", "2131689962");
        hashMap22.put("icon", "icon_saab");
        hashMap22.put("areaId", "EUROPE");
        hashMap22.put("sname", context.getString(R.string.SAAB));
        hashMap22.put("sname_zh", "SABO");
        arrayList.add(hashMap22);
        HashMap hashMap23 = new HashMap();
        hashMap23.put("softPackageId", "SEAT");
        hashMap23.put("name", context.getString(R.string.SEAT));
        hashMap23.put("name_zh", "2131689974");
        hashMap23.put("icon", "icon_seat");
        hashMap23.put("areaId", "EUROPE");
        hashMap23.put("sname", context.getString(R.string.SEAT));
        hashMap23.put("sname_zh", "XITE");
        arrayList.add(hashMap23);
        HashMap hashMap24 = new HashMap();
        hashMap24.put("softPackageId", "SPRINTER");
        hashMap24.put("name", context.getString(R.string.SPRINTER));
        hashMap24.put("name_zh", "2131689998");
        hashMap24.put("icon", "icon_sprinter");
        hashMap24.put("areaId", "EUROPE");
        hashMap24.put("sname", context.getString(R.string.SPRINTER));
        hashMap24.put("sname_zh", "BENCHISHANGWUCHE");
        arrayList.add(hashMap24);
        HashMap hashMap25 = new HashMap();
        hashMap25.put("softPackageId", "SKODA");
        hashMap25.put("name", context.getString(R.string.SKODA));
        hashMap25.put("name_zh", "2131689988");
        hashMap25.put("icon", "icon_skoda");
        hashMap25.put("areaId", "EUROPE");
        hashMap25.put("sname", context.getString(R.string.SKODA));
        hashMap25.put("sname_zh", "SIKEDA");
        arrayList.add(hashMap25);
        HashMap hashMap26 = new HashMap();
        hashMap26.put("softPackageId", "SMART");
        hashMap26.put("name", context.getString(R.string.SMART));
        hashMap26.put("name_zh", "2131689990");
        hashMap26.put("icon", "icon_smart");
        hashMap26.put("areaId", "EUROPE");
        hashMap26.put("sname", context.getString(R.string.SMART));
        hashMap26.put("sname_zh", "JINGLINGSMART");
        arrayList.add(hashMap26);
        HashMap hashMap27 = new HashMap();
        hashMap27.put("softPackageId", "VAUXHALL");
        hashMap27.put("name", context.getString(R.string.VAUXHALL));
        hashMap27.put("name_zh", "2131690051");
        hashMap27.put("icon", "icon_vauxhall");
        hashMap27.put("areaId", "EUROPE");
        hashMap27.put("sname", context.getString(R.string.VAUXHALL));
        hashMap27.put("sname_zh", "WOKESIHAOER");
        arrayList.add(hashMap27);
        HashMap hashMap28 = new HashMap();
        hashMap28.put("softPackageId", "VAZ");
        hashMap28.put("name", context.getString(R.string.VAZ));
        hashMap28.put("name_zh", "2131690053");
        hashMap28.put("icon", "icon_vaz");
        hashMap28.put("areaId", "EUROPE");
        hashMap28.put("sname", context.getString(R.string.VAZ));
        hashMap28.put("sname_zh", "VAZ");
        arrayList.add(hashMap28);
        HashMap hashMap29 = new HashMap();
        hashMap29.put("softPackageId", "VOLVO");
        hashMap29.put("name", context.getString(R.string.VOLVO));
        hashMap29.put("name_zh", "2131690055");
        hashMap29.put("icon", "icon_volvo");
        hashMap29.put("areaId", "EUROPE");
        hashMap29.put("sname", context.getString(R.string.VOLVO));
        hashMap29.put("sname_zh", "WOERWOCHEXI");
        arrayList.add(hashMap29);
        HashMap hashMap30 = new HashMap();
        hashMap30.put("softPackageId", "VW");
        hashMap30.put("name", context.getString(R.string.VW));
        hashMap30.put("name_zh", "2131690057");
        hashMap30.put("icon", "icon_vw");
        hashMap30.put("areaId", "EUROPE");
        hashMap30.put("sname", context.getString(R.string.VW));
        hashMap30.put("sname_zh", "DAZHONG");
        arrayList.add(hashMap30);
        return arrayList;
    }
}
